### ISSUE TITLE
Improper generated enum values

### ISSUE THREAD

**Issue by CADBIMDeveloper** [elringus/bootsharp#129]
Hi @elringus ,

There is a problem with enum values handling in the bootsharp. Let's say, I have the following backend:
```cs
public enum Foo
{
	Value1 = 1,
	
	Value2 = 2
}

public static partial class Program
{
	public static void Main ()
	{
	}

	[JSInvokable]
	public static Foo Test() => Foo.Value1;
}
```

It generates the following definitions:
```js
const Global = {
    ...
    test: () => deserialize(getExports().Program.Test()),
    Foo: { "0": "Value1", "1": "Value2", "Value1": 0, "Value2": 1 }
};
```

So 
```js 
console.log(Global.test() === Global.Foo.Value1);
``` 
prints `false`

Thank you!

**Comment by elringus** [comment]
Yep, this is one of the breaking changes mentioned in #123. 

![426f29ee670e6a1ef62647adae767d8c](https://github.com/elringus/bootsharp/assets/2056864/6d60f602-adfd-46ef-b42f-8a04ba256a75)

**Comment by elringus** [comment]
Ah, my bad, you're assigning custom enum indexes in C#. I'm probably hot handling that when generating JS enums. Will look into that, thanks for the report!
