### ISSUE TITLE
Disabling JavaScript disables .NET Timers

### ISSUE THREAD

**Issue by SavoInfostream** [elringus/bootsharp#149]
Hello,
Just a random question I need help with. 
Why is it that when I disable JS on the page, the `PeriodicTimer`s and `Timer`s in my app stop emitting events?
I am pretty sure my code works is not causing this.

**Comment by elringus** [comment]
No idea. If it's somehow related to .NET/WASM, you'd better ask on the runtime repo. Bootsharp is just an interop layer.
