### ISSUE TITLE
 use visual studio build has error

### ISSUE THREAD

**Issue by yanwuguangjun** [elringus/bootsharp#164]
at new  version 0.3.3.0

use cli cmd "dotnet publish" is fine
 use visual studio build has error

`未能从程序集 C:\Users\Administrator\.nuget\packages\bootsharp\0.3.3\build\..//tasks/Bootsharp.Publish.dll 加载任务“Bootsharp.Publish.BootsharpEmit”。Could not load file or assembly 'System.Runtime, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. 系统找不到指定的文件。 请确认 <UsingTask> 声明正确，该程序集及其所有依赖项都可用，并且该任务包含实现 Microsoft.Build.Framework.ITask 的公共类。`

 but  it works on Web Browser;

I think the point is   `System.Runtime`

**Comment by elringus** [comment]
See #137
