### ISSUE TITLE
Support .NET -> JavaScript streaming

### ISSUE THREAD

**Issue by elringus** [elringus/bootsharp#19]
While Blazor provide APIs for raw byte streaming between .NET and JavaScript ([doc](https://docs.microsoft.com/en-us/aspnet/core/blazor/javascript-interoperability/call-javascript-from-dotnet?view=aspnetcore-6.0#stream-from-net-to-javascript)), .NET to JS streaming relies on browser-only `Response` type:

https://github.com/Elringus/DotNetJS/blob/97647de97a9ffe0aafdc1941a947f79f9816b9d8/JavaScript/dotnet-js-interop/src/main.js#L458

Associated calls in the runtime:
https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Components/Web.JS/src/GlobalExports.ts#L80
https://github.com/dotnet/aspnetcore/blob/release/6.0/src/Components/Web.JS/src/StreamingInterop.ts#L24

We have to add environment-agnostic streaming implementation and test it:
https://github.com/Elringus/DotNetJS/blob/97647de97a9ffe0aafdc1941a947f79f9816b9d8/JavaScript/dotnet-runtime/test/interop.js#L125

**Comment by Aloento** [comment]
Maybe this:
https://wicg.github.io/compression/#example-deflate-compress
