### ISSUE TITLE
Git rid of eval() in WASM wrapper

### ISSUE THREAD

**Issue by Aragas** [elringus/bootsharp#51]
Hi again!
I used DotNetJS to create a library that exposes some common functions that we share across C# executables and an Electron app to ensure the behaviour is identical.
The problem is, the electron's app ([Vortex](https://github.com/Nexus-Mods/Vortex)) is blocking `eval` execution due to it's CSP. I did earlier some investigation about this, but I would like to double check! Is `eval` critical for the runtime to work or is it used only for debugging? Could we strip it's usage with some conditionals?

- [x] Waiting for https://github.com/dotnet/runtime/pull/74441

**Comment by Aragas** [comment]
https://github.com/dotnet/runtime/issues/68374
https://github.com/dotnet/runtime/issues/59416
https://github.com/dotnet/aspnetcore/issues/37787

Based on those issues, it's fixable, but not done yet, it seems

**Comment by Elringus** [comment]
> I think that there's an additional `eval` call in function `Function.apply(Function, i);`

Right, that aligns with the mono issue you've mentioned previously (https://github.com/dotnet/runtime/issues/68374); they've also mentioned the same line and a couple of others. Guess we'd have to wait when it's solved.

**Comment by Aragas** [comment]
https://github.com/dotnet/runtime/issues/68374#issuecomment-1149742636
I guess the variable could be set at build time?

**Comment by Elringus** [comment]
> [dotnet/runtime#68374 (comment)](https://github.com/dotnet/runtime/issues/68374#issuecomment-1149742636) I guess the variable could be set at build time?

Probably here: https://github.com/Elringus/DotNetUMD/blob/release/6.0/src/mono/wasm/wasm.proj#L74
Though, I don't think just setting this var will strip all the evals, as they've mentioned they're using them to generate interop functions.

**Comment by Aragas** [comment]
As I understand, will be fixed once this is done https://github.com/dotnet/runtime/pull/74441

**Comment by Aragas** [comment]
Okay, the deed is done, they merged the PR! Is it possible to switch to the new code?

**Comment by Elringus** [comment]
I'll look into this once the change is available in a shipped .NET, which will probably be .NET 8 (judging by the milestone associated with the PR).
