### ISSUE TITLE
Migrate to the new JS interop layer

### ISSUE THREAD

**Issue by elringus** [elringus/bootsharp#75]
It looks like at some point (.NET 7?) a new JS interop layer will be introduced: 

 - https://github.com/dotnet/runtime/pull/66304
 - https://github.com/dotnet/runtime/pull/71332

**Comment by Aragas** [comment]
They merged those PR's and added samples of the new interop usage https://github.com/dotnet/runtime/pull/74371

**Comment by Elringus** [comment]
I've looked into the new interop a bit and found an issue which I believe is blocking the migration: the new interop uses source generators, while our solution also generates stuff and it's currently not possible to chain them. It looks like the feature is being considered, but not in the works yet (https://github.com/dotnet/roslyn/issues/57239), so it may take a while.
